# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'T6SolutionDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for T6SolutionDemo
pod 'Alamofire', '~> 4.7'
pod 'JTMaterialTransition'
pod 'DatePickerDialog'
pod 'ActionSheetPicker-3.0'

  target 'T6SolutionDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'T6SolutionDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TestDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestDemo

end
